name: Node Deployment

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:          
      - name: Deploy to Server 
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{secrets.HOST_USERNAME}}
          key: ${{secrets.PRIVATE_KEY}}
          port: 22
          script: |
            ssh-add ~/.ssh/githubAuth
            cd ~/../NODE_APPS/ebha_3005
            git pull origin release
            npm install --only=production
            NODE_ENV=production pm2 restart ebha_3003 --update-env
            


          
